### PR TITLE
Object Assigns

### PR DESCRIPTION
**Pull request by pi0**
@egoist Regarding Issue #1, I've just prepared this PR (seems a little late). PLEASE consider this is the only feature that we want from polyfill and is as important as promises. Overhead is just an additional `_extend` function vs adding entire polyfill dependency and just works out of the box for users coming from Nuxt.js without need to any extra hacks.

### CODE REVIEW

**Comment by egoist** [comment]
I'm not sure about this since it says > If you are authoring an application, rather than a library, it is recommended that you use the Object.assign polyfill instead.

/cc @vuejs/collaborators

**Comment by pi0** [comment]
@egoist This is the same thing for [babel-plugin-transform-runtime](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-runtime) (This plugin is recommended in a library/tool) :)) Anyway i agree things like this should be added with care.

**Comment by posva** [comment]
I'm usually against these things because not everyone needs to support IE but the support for IE 9 is already added at https://github.com/vuejs/babel-preset-vue-app/blob/master/index.js#L16 so we should support it completely. Because of this, I think we should specify that this preset adds many polyfills in order to support old browsers like IE and that it may be too much for some people

**Comment by pi0** [comment]
@posva If you see issue #1 this is the exact reason i started to suggest this transform :)) Not only IE 9 but many devices such as ios 8 and android up to 5.1 are affected! Also about overhead this is not so much as we are already transforming generators too. (this common function only adds few more bytes for _extend implementation)

**Comment by atinux** [comment]
The error with ios < 9 and android < 5.1 makes it really important from my point of view since it's not only IE9 support.

**Comment by egoist** [comment]
@Atinux sure, the question is whether it should be done in this repo, we will need many polyfills besides `Object.assign` if you target these platforms.

**Comment by egoist** [comment]
Fixed in `v1.1.0`

**Pull request closed without merging**
